### ISSUE TITLE
Paths

### ISSUE THREAD

**Issue by SeSamSeg** [toalex77/steam-legendary-wrapper#1]
I got it to work on Manjaro

Thing I had to change:
`STEAM_ROOT="${HOME}/.local/share/Steam`
and
`PROTON_CUSTOM_BASEDIR="/usr/share/steam/compatibilitytools.d`
(this is the proton-ge folder from AUR)

There was also a problem with the `if [ "$( file "${legendary_bin}" | grep -c "ELF" )" -eq 0 ]` when running it from Steam. The custom compiled legendary from /opt/Heroic was selected, but the if failed. I worked when not run from Steam. I disabled the check and got it to run smoothly and with steam controller support.

**Comment by toalex77** [comment]
I'll investigate. Thanks.
Have you installed Steam and Proton GE from repositories?
I'll try to setup a virtual machine to reproduce the issues.

**Comment by SeSamSeg** [comment]
Yes
Steam-manjaro or Steam native from repo (steam-manjaro is already installed)
Proton-ge from aur:
https://aur.archlinux.org/packages/proton-ge-custom-bin/

**Comment by toalex77** [comment]
Can you test branch BUGFIX/#1?
You can get it from git (git checkout BUGFIX/#1), if you cloned the repository, or you can download it directly from here https://raw.githubusercontent.com/toalex77/steam-legendary-wrapper/BUGFIX/%231/steam-legendary-wrapper.sh  

I have fixed the management of paths where the wrapper search for Proton, and I had to replace the "file" command with "ldd", because it seems that it has problems with seccomp policies when it is called inside a sandboxed environment  under Steam. I know that I can use "file -S", but ldd seems to run with less issues.

**Comment by SeSamSeg** [comment]
Thanks, it's working great now.
It seems game data is stored in ${HOME}/.local/share/Steam, but everything the script checks for is double and also in ${HOME}/.steam/root so the check of STEAM_ROOT isn't necessary.

**Comment by toalex77** [comment]
Yes, I know... it's only a, scrupulous, little bit paranoid check.
Anyway I reviewed further that piece of code, and now... is more paranoid.
